import type { NextPage } from "next";
import Head from "next/head";
import { makeStyles } from "@mui/styles";
import { Typography, Grid, Hidden } from "@mui/material";
import { Theme } from "@mui/system";
import { useMobileVisible } from "../hooks/useMobileVisible";
import Form from "../components/form/form";
import Image from "next/image";
import Img from "../assets/images/email.jpeg";
import IssuesList from "../components/sections/issuesList";

const useStyles = makeStyles((theme: Theme) => ({
    mainWrapper: {
        margin: "0 15%",
        width: "auto",
        [theme.breakpoints.down("sm")]: {
            paddingTop: "10vh",
            margin: "0 5%",
            flexDirection: "column",
        },
    },
    infoWrapper: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    description: {
        margin: "25px 0",
        paddingLeft: 25,
        borderLeft: `2px solid ${theme.palette.secondary.main}`,
    },
}));

const Home: NextPage = () => {
    const classes = useStyles();

    const isMobileVisible = useMobileVisible();

    return (
        <>
            <Head>
                <title>GamedevJS - Weekly</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container className={classes.mainWrapper} rowSpacing={4}>
                <Grid item xs={12} md={6} className={classes.infoWrapper}>
                    <Typography variant="h4">{"Weekly newsletter about HTML5 Game Development"}</Typography>
                    <Typography variant="subtitle1" className={classes.description}>
                        {
                            "Subscripe to the weekly, free newsletter all about HTML5 Game Development, sent every Friday. Join over 7000 gamedev subscribers. No spam, open for related sponsorship opportunities and job listings."
                        }
                    </Typography>
                    <Form
                        label={"sample@email.com"}
                        width={"75%"}
                        formOnTheTop
                        borderColor={isMobileVisible ? "#93bcd8" : "#ff9900"}
                        labelColor={"#000"}
                    />
                </Grid>
                <Hidden mdDown>
                    <Grid
                        item
                        xs={12}
                        md={6}
                        style={{ display: "flex" }}
                        justifyContent={"center"}
                        alignItems={"center"}>
                        <Image src={Img} alt={"email"} width={300} height={300} />
                    </Grid>
                </Hidden>
                <Grid item xs={12} display="flex" flexDirection="column">
                    <IssuesList />
                </Grid>
            </Grid>
        </>
    );
};

export default Home;
