import type { NextPage } from "next";
import Head from "next/head";
import { makeStyles } from "@mui/styles";
import { Typography, Grid, Hidden, Divider, ListItem, Button, List } from "@mui/material";
import { Theme } from "@mui/system";
import { Fragment } from "react";
import Form from "../components/form/form";
import Image from "next/image";
import Img from "../assets/images/email.jpeg";
import Link from "next/link";

const useStyles = makeStyles((theme: Theme) => ({
    mainWrapper: {
        margin: "0 15%",
        width: "auto",
        [theme.breakpoints.down("sm")]: {
            paddingTop: "10vh",
            margin: "0 5%",
            flexDirection: "column",
        },
    },
    infoWrapper: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        // "& :nth-child(3)": {
        //     backgroundColor: "green",
        //     width: "100%",
        // },
    },
    description: {
        margin: "25px 0",
        paddingLeft: 25,
        borderLeft: `2px solid ${theme.palette.secondary.main}`,
    },
    divider: {
        borderColor: theme.palette.secondary.light,
    },
    listItem: {
        padding: "12px 0",
    },
    listItemLink: {
        color: theme.palette.secondary.light,
        cursor: "pointer",
    },
    issueBtn: {
        marginTop: 25,
        borderRadius: 25,
        color: "#fff",
        backgroundColor: theme.palette.secondary.light,
        padding: "5px 30px",
        borderColor: theme.palette.secondary.main,
        alignSelf: "center",
        [theme.breakpoints.down("sm")]: {
            padding: "10px 50px",
        },
    },
}));

const emails = [
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
    {
        date: "21/01/2022",
        title: "Issue #420 Web GameDev Summit, Make JavaScript Games, and Vampires Survivors",
        href: "/#420",
    },
];

const Home: NextPage = () => {
    const classes = useStyles();

    return (
        <>
            <Head>
                <title>GamedevJS - Weekly</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container className={classes.mainWrapper} rowSpacing={4}>
                <Grid item xs={12} md={6} className={classes.infoWrapper}>
                    <Typography variant="h4">{"Weekly newsletter about HTML5 Game Development"}</Typography>
                    <Typography variant="subtitle1" className={classes.description}>
                        {
                            "Subscripe to the weekly, free newsletter all about HTML5 Game Development, sent every Friday. Join over 7000 gamedev subscribers. No spam, open for related sponsorship opportunities and job listings."
                        }
                    </Typography>
                    <Form label={"sample@email.com"} width={"75%"} borderColor={"orange"} labelColor={"#000"} />
                </Grid>
                <Hidden mdDown>
                    <Grid
                        item
                        xs={12}
                        md={6}
                        style={{ display: "flex" }}
                        justifyContent={"center"}
                        alignItems={"center"}>
                        <Image src={Img} alt={"email"} width={300} height={300} />
                    </Grid>
                </Hidden>
                <Grid item xs={12} display="flex" flexDirection="column">
                    <Typography variant="h4" marginTop={4} marginBottom={2}>
                        {"Gamedev.js Weekly newsletter archive"}
                    </Typography>
                    <Typography variant="subtitle1" marginBottom={2}>
                        {"Check out any of the recent 10 entries:"}
                    </Typography>
                    <List>
                        <Divider classes={{ root: classes.divider }} />
                        {emails.map(({ href, title, date }, id) => (
                            <Fragment key={id}>
                                <ListItem className={classes.listItem}>
                                    <Typography variant={"subtitle1"}>
                                        {`${date} -`}{" "}
                                        {
                                            <Link href={href} passHref>
                                                <span className={classes.listItemLink}>{title}</span>
                                            </Link>
                                        }
                                    </Typography>
                                </ListItem>
                                <Divider classes={{ root: classes.divider }} />
                            </Fragment>
                        ))}
                    </List>
                    <Button className={classes.issueBtn} variant="outlined">
                        {"View all issues"}
                    </Button>
                </Grid>
            </Grid>
        </>
    );
};

export default Home;
