import type { NextPage } from "next";
import Head from "next/head";
import { makeStyles } from "@mui/styles";
// import { Typography, Grid, Button, Box } from "@mui/material";
import { Theme } from "@mui/system";
import Wrapper from "../layouts/paragraphWrapper";

const useStyles = makeStyles((theme: Theme) => ({}));

const sponsorsInfo = [
    {
        title: "Sponsor",
        description1:
            "Are you interested in sponsoring the Gamedev.js Weekly newsletter? That's great, thank you! Check the detail below:",
    },
    {
        title: "Advertisements",
        description1:
            "We are open to include paid advert items in the newsletter. They have to be related to game development, front-end / JavaScript, or programming in general, and are placed in a related section, usually Tools or Resources. An advert item is text based, and consists of a title (recommended 80 characters), destination url, and description (up to 160 characters, but can be longer when needed). It is always marked with light blue background to stand out from the regular newsletter items.",
    },
    {
        title: "Job openings",
        description1:
            "They look and work the same as regular advertisements, but dont't have a light blue background, and are always placed in the Jobs section of a given newsletter issue.",
        description2:
            "Available options for both types listed above included one-time spot, a month-long campaign, and longer placements as well - for detailed pricing please get in touch.",
    },
    {
        title: "Donations",
        description1: "If you're interested in a one-time donation, then please visit given page for details.",
    },
];

const Sponsor: NextPage = () => {
    const classes = useStyles();

    return (
        <>
            <Head>
                <title>GamedevJS - Weekly - Sponsor</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper data={sponsorsInfo} titlePage="Sponsor" />
        </>
    );
};

export default Sponsor;
