import type { NextPage } from "next";
import Head from "next/head";
import { makeStyles } from "@mui/styles";
import { Typography, Grid, Button } from "@mui/material";
import { Theme } from "@mui/system";

const useStyles = makeStyles((theme: Theme) => ({
    mainWrapper: {
        margin: "0 15%",
        width: "auto",
    },
    contactBtn: {
        borderRadius: 25,
        backgroundColor: "yellow",
        textTransform: "capitalize",
        padding: "5px 60px",
        borderColor: "orange",
    },
}));

const Sumbit: NextPage = () => {
    const classes = useStyles();

    return (
        <>
            <Head>
                <title>GamedevJS - Weekly - Submit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container className={classes.mainWrapper} rowSpacing={4}>
                <Grid item xs={9}>
                    <Typography variant={"h5"}>{"Submit your content"}</Typography>
                    <Typography variant={"subtitle1"} style={{ margin: "25px 0" }}>
                        {
                            "Do you have anything you want to share with the HTML5 Game Development community through the newsletter? If yes, then please let us know by contanting us directly with all the details! Share interesting resources with fellow folks, either yours or anything you have found online that fit the topic. Content submitted by readers ends up in a nesletter once every 2 - 3 issues on average, and we'd love to see even more involvement from you!"
                        }
                    </Typography>
                    <Typography variant={"subtitle1"}>
                        {
                            "If you're interested in a sponsorship or a donation, then please visit given pages respectively"
                        }
                    </Typography>
                </Grid>
                <Grid item xs={12} style={{ display: "flex" }} justifyContent="center">
                    <Button variant="outlined" className={classes.contactBtn}>
                        {"Contact us"}
                    </Button>
                </Grid>
            </Grid>
        </>
    );
};

export default Sumbit;
