import type { NextPage } from "next";
import Head from "next/head";
import { makeStyles } from "@mui/styles";
import { Typography, Grid, Button } from "@mui/material";
import { Theme } from "@mui/system";
import Wrapper from "../layouts/paragraphWrapper";

const useStyles = makeStyles((theme: Theme) => ({}));

const Sumbit: NextPage = () => {
    const classes = useStyles();

    const submitInfo = [
        {
            title: "Submit your content",
            description1:
                "Do you have anything you want to share with the HTML5 Game Development community through the newsletter? If yes, then please let us know by contanting us directly with all the details! Share interesting resources with fellow folks, either yours or anything you have found online that fit the topic. Content submitted by readers ends up in a nesletter once every 2 - 3 issues on average, and we'd love to see even more involvement from you!",
            description2:
                "If you're interested in a sponsorship or a donation, then please visit given pages respectively",
        },
    ];

    return (
        <>
            <Head>
                <title>GamedevJS - Weekly - Submit</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper data={submitInfo} titlePage="Submit your content" />
        </>
    );
};

export default Sumbit;
